name: Component Notification

on:
  push:
    paths:
      - 'src/components/**'

env:
  URL: https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git

jobs:
  
  notify:
    runs-on: ubuntu-latest

    permissions:
      deployments: write
      contents: write
      statuses: write
      actions: write
      checks: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Extract Component Name
        id: extract
        run: |
          FILE_PATH=$(git diff --name-only HEAD^ -- 'src/components/')
          if [[ -z "$FILE_PATH" ]]; then
            echo "No component path found. Skipping the rest of the steps."
            exit 0
          fi
          echo "::set-output name=component_path::$FILE_PATH"

      - name: Update README.md
        if: steps.extract.outputs.component_name != ''
        run: |
          COMPONENT_PATH="${{ steps.extract.outputs.component_path }}"
          REPO_PATH="https://github.com/${{ github.repository }}/blob/${{ github.sha }}/$COMPONENT_PATH"
          COMPONENT_LINK="- New component added: [${COMPONENT_PATH}](${REPO_PATH})"
          sed -i "s/<!-- COMPONENT_LIST -->/$COMPONENT_LINK\\n<!-- COMPONENT_LIST -->/" README.md
          cat README.md
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit -am "🚀 New component added" --no-verify
          git push ${{ env.URL }}