name: Component Notification

on:
  push:
    paths:
      - 'src/components/**'

env:
  URL: https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git

jobs:
  
  notify:
    runs-on: ubuntu-latest

    permissions:
      deployments: write
      contents: write
      statuses: write
      actions: write
      checks: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Extract Component Name
        id: extract
        run: |
          FILE_PATH=$(git diff --name-only HEAD^ -- 'src/components/')
          if [[ -z "$FILE_PATH" ]]; then
            echo "No component path found. Skipping the rest of the steps."
            exit 0
          fi
          echo "COMPONENT_PATH=$FILE_PATH" >> $GITHUB_ENV

          NAME=$(echo "$FILE_PATH" | grep -o -P "(?<=src/components/).*(?=\.(js|jsx|ts|tsx))")
          echo "COMPONENT_NAME=$NAME" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          if [[ -z "${{ env.COMPONENT_PATH }}" ]]; then
            echo "No component path found. Skipping the rest of the steps."
            exit 0
          fi

          REPO_PATH="https://github.com/${{ github.repository }}/blob/${{ github.sha }}/${{ env.COMPONENT_PATH }}"
          
          COMPONENT_LINK="- 🧩 New component added: [${{ env.COMPONENT_PATH }}]($REPO_PATH)"

          echo $COMPONENT_LINK
          
          sed -i "s#<!-- COMPONENT_LIST -->#$COMPONENT_LINK\\n<!-- COMPONENT_LIST -->#" README.md
          
          cat README.md
          
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit -am "🧩 New component added" --no-verify
          git push ${{ env.URL }}

      - name: Send email to notify new component
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.USER_EMAIL }}
          password: ${{ secrets.PASS_EMAIL }}
          subject: "🧩 New component has been added!"
          from: React Native Testing Project <${{ secrets.USER_EMAIL }}>
          body: |
            Hey there,

            The component (${{ env.COMPONENT_NAME }}) has been added to the repository!

            Please check the README.md - https://github.com/${{ github.repository }}/blob/master/README.md" file to see the new component.

            If you haven't cloned the repository yet, you can do it by running the following command: git clone git@github.com:aiherrera/reactnative-template-starter.git
            If you already cloned the repository, you can pull the latest changes by running the following command: git pull

            Happy testing!
            Alain
          to: alain.iherrera@gmail.com